### ISSUE TITLE
C++ Regex

### ISSUE THREAD

**Issue by DmyPel** [Progressor/ProgressorExecutor#6]
Is it possible to use regex?
Because I used it, but it never matched. So I tried the same code with an online compiler and it worked.

**Comment by StrubT** [comment]
it's possible, there seems to be an error with boolean returns in C++ (bug reported via email)
http://progressor.ti.bfh.ch/exercise/edit/uF9nQdfXtaZbXkRB8

**Comment by StrubT** [comment]
seems to work now, re-open if next release does not fix the issue for you
