### ISSUE TITLE
C# return List<string>

### ISSUE THREAD

**Issue by DmyPel** [Progressor/ProgressorExecutor#8]
When I want to return a List, the compiler gives me this as a error: "System.Collections.Generic.List`1[System.String]"
How should I format the list, so the compiler can show me the content of the list?

**Comment by StrubT** [comment]
confirmed, reported via email
http://progressor.ti.bfh.ch/exercise/edit/usdB5JHLfEkRizB8M

**Comment by StrubT** [comment]
We somehow forgot to allow for collection return types.
Added comparison, formatting & unit tests for all languages.
